# Generated by Django 3.1.3 on 2020-11-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad_economica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Actividad_economica',
            },
        ),
        migrations.CreateModel(
            name='Area_desempeno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Area_desempeno',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('link_emp', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Forma_juridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_juridica', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Forma_juridica',
            },
        ),
        migrations.CreateModel(
            name='Nivel_estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Nivel_estudio',
            },
        ),
        migrations.CreateModel(
            name='Representante_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=200)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Representante_empresa',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('estatus', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Usuario_desempeno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desempleo.area_desempeno')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desempleo.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Usuario_desempeno',
            },
        ),
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_s', models.DateTimeField()),
                ('id_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desempleo.empresa')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desempleo.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Seleccion',
            },
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desempleo.nivel_estudio')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desempleo.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Formacion',
            },
        ),
        migrations.CreateModel(
            name='Empresa_actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desempleo.actividad_economica')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desempleo.empresa')),
            ],
            options={
                'verbose_name_plural': 'Empresa_actividad',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_forma_juridica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desempleo.forma_juridica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_representante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Desempleo.representante_empresa'),
        ),
    ]
